on:
  push:
  release:
    types: [ created ]
name: Publish
jobs:
  publish:
    name: Publish
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties', '**/gradle/libs.versions.toml') }}
      - name: Cache Template
        uses: actions/cache@v3
        with:
          path: template
          key: template-${{ hashFiles('template/**', 'build.gradle.kts', 'gradle.properties', 'gradle/libs.versions.toml') }}
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Publish
        run: |
          ./gradlew --no-daemon publish
        env:
          REPOSILITE_PASSWORD: ${{ secrets.REPOSILITE_PASSWORD }}
